version: '3'
services:
  api:
    image: node:10
    ports:
      - 8080:8080
    volumes:
      - ./api:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
    environment:
      #mailhog
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_DRIVER: smtp
      #app
      APP_PORT: 8080
      #db
      DB_URI: db
      DB_PORT: 27017
      DB_NAME: dbname
      DB_AUTH_USERNAME: root
      DB_AUTH_PASSWORD: root
    links:
      - db
  auth:
    image: node:10
    ports:
      - 8082:8082
    volumes:
      - ./authorization:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
    environment:
      #mailhog
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_DRIVER: smtp
      #app
      APP_PORT: 8082
      #db
      DB_URI: db
      DB_PORT: 27017
      DB_NAME: auth_dbname
      DB_AUTH_USERNAME: root
      DB_AUTH_PASSWORD: root
    links:
      - db
#  mailhog:
#    image: mailhog/mailhog
#    ports:
#      - 8025:8025
#      - 1025:1025
  db:
    image: mongo
#    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: dbname
    ports:
      - 27017:27017
  db-ui:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    ports:
      - 8081:8081
    links:
      - db
